# Generated by Django 3.0.7 on 2020-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_link', models.TextField()),
                ('share_link', models.CharField(max_length=16)),
                ('creation_timestamp', models.DateTimeField()),
            ],
        ),
    ]
