# Generated by Django 3.0.7 on 2020-06-29 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='share_link',
            new_name='share_id',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
