# Generated by Django 3.0.7 on 2020-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200629_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='share_id',
            field=models.CharField(max_length=32),
        ),
    ]
