# Generated by Django 3.0.7 on 2020-06-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200629_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='store_link',
            new_name='file_name',
        ),
    ]
